# Generated by Django 4.1.dev20211005113041 on 2021-10-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('professor', models.CharField(max_length=50)),
                ('days', models.CharField(max_length=5)),
                ('class_size', models.IntegerField()),
            ],
        ),
    ]
